version: "3.7"
services:
  prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "28083:58083"
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
